version: '3'
services:
  web:
    image: ayushdock/vpp:latest 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:80
    volumes:
      - /app/node_modules
      - .:/app
    